name: uptodo
description: "UpTodo | Get your daily reminder of tasks"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

# -------------- Packages -------------- #
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  google_fonts: 6.1.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  go_router: ^14.0.2
  intl: ^0.19.0
  uuid: ^4.4.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  introduction_screen: ^3.1.14
  firebase_storage: ^11.6.9
  path: ^1.8.3
  image_picker: ^1.0.8
  dartz: ^0.10.1
  get_it: ^7.6.7
  table_calendar: ^3.1.1
  flutter_dnd: ^0.1.4+1
  app_usage: ^3.0.1
  device_apps: ^2.2.0


# -------------- Packages End -------------- #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  # -------------- Local Assets -------------- #

  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/icons/

  # -------------- Local Fonts -------------- #
