// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV8W4zLeILbhGB98Easf1LfAJww64peYU',
    appId: '1:34151291925:web:f811fd43c48713fa4bc21c',
    messagingSenderId: '34151291925',
    projectId: 'uptodo-bloc',
    authDomain: 'uptodo-bloc.firebaseapp.com',
    storageBucket: 'uptodo-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ppSqvGvF30gV44kf2--MWEH6vug9xj8',
    appId: '1:34151291925:android:a30e1523a778fb404bc21c',
    messagingSenderId: '34151291925',
    projectId: 'uptodo-bloc',
    storageBucket: 'uptodo-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR7pHxGm1qTZIaXm1nrw0hdqUv2C5zNqM',
    appId: '1:34151291925:ios:4f959265f70cea8e4bc21c',
    messagingSenderId: '34151291925',
    projectId: 'uptodo-bloc',
    storageBucket: 'uptodo-bloc.appspot.com',
    iosBundleId: 'com.devbymehar.UpTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR7pHxGm1qTZIaXm1nrw0hdqUv2C5zNqM',
    appId: '1:34151291925:ios:4f959265f70cea8e4bc21c',
    messagingSenderId: '34151291925',
    projectId: 'uptodo-bloc',
    storageBucket: 'uptodo-bloc.appspot.com',
    iosBundleId: 'com.devbymehar.UpTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV8W4zLeILbhGB98Easf1LfAJww64peYU',
    appId: '1:34151291925:web:dd7cc6c9871ec1384bc21c',
    messagingSenderId: '34151291925',
    projectId: 'uptodo-bloc',
    authDomain: 'uptodo-bloc.firebaseapp.com',
    storageBucket: 'uptodo-bloc.appspot.com',
  );
}
